{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "powerdns-operator.fullname" . }}
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "powerdns-operator.labels" . | nindent 4 }}
  {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "powerdns-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: http-metrics
    interval: {{ .Values.metrics.serviceMonitor.scrapeInterval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    {{- if .Values.metrics.serviceMonitor.scheme }}
    scheme: {{ .Values.metrics.serviceMonitor.scheme }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings: {{- toYaml .Values.metrics.serviceMonitor.metricRelabelings | nindent 6 }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.relabelings }}
    relabelings: {{ toYaml .Values.metrics.serviceMonitor.relabelings | nindent 6 }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml .Values.metrics.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
{{- end }}