# This rule is not used by the project powerdns-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dns.cav.enablers.ob resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: powerdns-operator
    app.kubernetes.io/managed-by: kustomize
  name: pdnsprovider-viewer-role
rules:
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - pdnsproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - pdnsproviders/status
  verbs:
  - get
