---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - clusterrrsets
  - clusterzones
  - pdnsproviders
  - rrsets
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - clusterrrsets/finalizers
  - clusterzones/finalizers
  - pdnsproviders/finalizers
  - rrsets/finalizers
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - clusterrrsets/status
  - clusterzones/status
  - pdnsproviders/status
  - rrsets/status
  - zones/status
  verbs:
  - get
  - patch
  - update
