# Cluster-Scoped Resource Examples for PowerDNS Operator
# These resources are available cluster-wide and typically managed by platform teams

---
# Example 1: Corporate Root Zone
# Main corporate domain managed at cluster level
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterZone
metadata:
  name: company.com
  labels:
    zone-type: corporate
    criticality: high
    team: platform
  annotations:
    description: "Main corporate domain zone"
    owner: "platform-team@company.com"
    backup-policy: "daily"
    compliance: "required"
spec:
  kind: Native
  nameservers:
    - ns1.company.com
    - ns2.company.com
    - ns3.company.com
  # SOA settings for corporate domain
  soa_edit_api: EPOCH
  account: "corporate"

---
# Example 2: Infrastructure Services Zone
# Zone for shared infrastructure services
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterZone
metadata:
  name: infra.company.com
  labels:
    zone-type: infrastructure
    criticality: high
    team: platform
  annotations:
    description: "Infrastructure services zone"
    purpose: "shared-services"
spec:
  kind: Native
  nameservers:
    - ns1.company.com
    - ns2.company.com
  soa_edit_api: EPOCH
  account: "infrastructure"

---
# Example 3: External Services Zone
# Zone for external-facing services
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterZone
metadata:
  name: services.company.com
  labels:
    zone-type: services
    exposure: external
    team: platform
  annotations:
    description: "External services zone"
    load-balancer: "enabled"
    cdn: "cloudflare"
spec:
  kind: Native
  nameservers:
    - ns1.company.com
    - ns2.company.com
  soa_edit_api: EPOCH
  account: "services"

---
# Example 4: Internal Services Zone
# Zone for internal microservices
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterZone
metadata:
  name: internal.company.com
  labels:
    zone-type: internal
    exposure: private
    team: platform
  annotations:
    description: "Internal services zone"
    network: "private"
    service-mesh: "istio"
spec:
  kind: Native
  nameservers:
    - ns1.company.com
    - ns2.company.com
  soa_edit_api: EPOCH
  account: "internal"

---
# Example 5: Regional Zone
# Zone for specific geographical region
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterZone
metadata:
  name: us-east.company.com
  labels:
    zone-type: regional
    region: us-east
    team: platform
  annotations:
    description: "US East region zone"
    geo-location: "us-east-1"
    failover-region: "us-west"
spec:
  kind: Native
  nameservers:
    - ns1.us-east.company.com
    - ns2.us-east.company.com
  soa_edit_api: EPOCH
  account: "us-east"

---
# ClusterRRset Examples
# DNS records that reference cluster-scoped zones

---
# Example 6: Corporate Website
# Main website A record
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: www-company-com
  labels:
    record-type: A
    service: website
    criticality: high
  annotations:
    description: "Main corporate website"
    cdn: "enabled"
    monitoring: "24x7"
spec:
  type: A
  ttl: 300
  records:
    - 203.0.113.10
    - 203.0.113.11
    - 203.0.113.12
  zoneRef:
    name: company.com
    kind: ClusterZone
  comment: "Load balanced web servers"

---
# Example 7: API Gateway
# API gateway endpoint
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: api-company-com
  labels:
    record-type: A
    service: api-gateway
    criticality: high
  annotations:
    description: "API gateway endpoint"
    rate-limiting: "enabled"
    authentication: "oauth2"
spec:
  type: A
  ttl: 120
  records:
    - 203.0.113.20
    - 203.0.113.21
  zoneRef:
    name: company.com
    kind: ClusterZone
  comment: "API gateway load balancers"

---
# Example 8: Mail Infrastructure
# Corporate mail servers
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: mail-company-com
  labels:
    record-type: MX
    service: email
    criticality: high
  annotations:
    description: "Corporate mail servers"
    backup-mx: "enabled"
    spam-filtering: "enabled"
spec:
  type: MX
  ttl: 3600
  records:
    - "10 mail1.company.com"
    - "20 mail2.company.com"
    - "30 mail-backup.company.com"
  zoneRef:
    name: company.com
    kind: ClusterZone
  comment: "Corporate mail infrastructure"

---
# Example 9: SPF Email Policy
# SPF record for email authentication
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: spf-company-com
  labels:
    record-type: TXT
    purpose: email-auth
    policy: spf
  annotations:
    description: "SPF email authentication policy"
    compliance: "required"
spec:
  type: TXT
  ttl: 3600
  records:
    - "v=spf1 include:_spf.google.com include:mailgun.org include:sendgrid.net ~all"
  zoneRef:
    name: company.com
    kind: ClusterZone
  comment: "SPF policy for email authentication"

---
# Example 10: DMARC Policy
# DMARC email policy
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: dmarc-company-com
  labels:
    record-type: TXT
    purpose: email-auth
    policy: dmarc
  annotations:
    description: "DMARC email policy"
    reporting: "enabled"
spec:
  type: TXT
  ttl: 3600
  records:
    - "v=DMARC1; p=quarantine; rua=mailto:dmarc@company.com; ruf=mailto:dmarc@company.com; sp=quarantine; adkim=r; aspf=r"
  zoneRef:
    name: company.com
    kind: ClusterZone
  comment: "DMARC policy for email protection"

---
# Example 11: Certificate Authority Authorization
# CAA record for SSL/TLS certificate control
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: caa-company-com
  labels:
    record-type: CAA
    purpose: ssl-policy
    security: certificate-control
  annotations:
    description: "Certificate Authority Authorization"
    approved-cas: "letsencrypt,digicert"
spec:
  type: CAA
  ttl: 3600
  records:
    - "0 issue letsencrypt.org"
    - "0 issue digicert.com"
    - "0 issue sectigo.com"
    - "0 iodef mailto:security@company.com"
  zoneRef:
    name: company.com
    kind: ClusterZone
  comment: "Restrict certificate issuance to approved CAs"

---
# Example 12: Infrastructure Services
# DNS records for shared infrastructure
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: vault-infra-company-com
  labels:
    record-type: A
    service: vault
    component: security
  annotations:
    description: "HashiCorp Vault service"
    high-availability: "enabled"
    backup: "automated"
spec:
  type: A
  ttl: 300
  records:
    - 10.100.1.10
    - 10.100.1.11
    - 10.100.1.12
  zoneRef:
    name: infra.company.com
    kind: ClusterZone
  comment: "Vault cluster endpoints"

---
# Example 13: Monitoring Infrastructure
# Monitoring and observability services
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: prometheus-infra-company-com
  labels:
    record-type: A
    service: prometheus
    component: monitoring
  annotations:
    description: "Prometheus monitoring service"
    federation: "enabled"
    retention: "90d"
spec:
  type: A
  ttl: 300
  records:
    - 10.100.2.10
    - 10.100.2.11
  zoneRef:
    name: infra.company.com
    kind: ClusterZone
  comment: "Prometheus monitoring cluster"

---
# Example 14: Container Registry
# Docker/OCI container registry
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: registry-infra-company-com
  labels:
    record-type: A
    service: registry
    component: artifacts
  annotations:
    description: "Container registry service"
    storage: "s3"
    cdn: "enabled"
spec:
  type: A
  ttl: 300
  records:
    - 10.100.3.10
    - 10.100.3.11
  zoneRef:
    name: infra.company.com
    kind: ClusterZone
  comment: "Container registry cluster"

---
# Example 15: External Load Balancer
# Public-facing load balancer
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: lb-services-company-com
  labels:
    record-type: A
    service: load-balancer
    exposure: public
  annotations:
    description: "External load balancer"
    ssl-termination: "enabled"
    waf: "enabled"
spec:
  type: A
  ttl: 60
  records:
    - 203.0.113.100
    - 203.0.113.101
  zoneRef:
    name: services.company.com
    kind: ClusterZone
  comment: "External load balancer endpoints"

---
# Example 16: Service Mesh Gateway
# Istio/Envoy gateway
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: gateway-internal-company-com
  labels:
    record-type: A
    service: gateway
    component: service-mesh
  annotations:
    description: "Service mesh ingress gateway"
    mesh: "istio"
    mTLS: "enabled"
spec:
  type: A
  ttl: 60
  records:
    - 10.200.1.10
    - 10.200.1.11
  zoneRef:
    name: internal.company.com
    kind: ClusterZone
  comment: "Service mesh gateway"

---
# Example 17: Regional API Endpoint
# Regional API for US East
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: api-us-east-company-com
  labels:
    record-type: A
    service: api
    region: us-east
  annotations:
    description: "US East API endpoint"
    latency-routing: "enabled"
    health-check: "enabled"
spec:
  type: A
  ttl: 60
  records:
    - 10.10.1.10
    - 10.10.1.11
  zoneRef:
    name: us-east.company.com
    kind: ClusterZone
  comment: "US East region API servers"

---
# Example 18: Wildcard SSL Certificate
# Wildcard record for SSL certificates
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: wildcard-company-com
  labels:
    record-type: A
    wildcard: "true"
    ssl: "wildcard"
  annotations:
    description: "Wildcard record for SSL certificates"
    certificate-type: "wildcard"
    auto-renewal: "enabled"
spec:
  type: A
  ttl: 300
  records:
    - 203.0.113.200
  zoneRef:
    name: company.com
    kind: ClusterZone
  comment: "Wildcard endpoint for SSL certificates"

---
# Example 19: IPv6 Support
# IPv6 records for dual-stack support
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: ipv6-www-company-com
  labels:
    record-type: AAAA
    service: website
    ip-version: ipv6
  annotations:
    description: "IPv6 records for main website"
    dual-stack: "enabled"
spec:
  type: AAAA
  ttl: 300
  records:
    - "2001:db8:85a3::1"
    - "2001:db8:85a3::2"
  zoneRef:
    name: company.com
    kind: ClusterZone
  comment: "IPv6 addresses for website"

---
# Example 20: Business Continuity
# Disaster recovery endpoint
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: dr-company-com
  labels:
    record-type: A
    service: disaster-recovery
    criticality: high
  annotations:
    description: "Disaster recovery endpoint"
    failover: "manual"
    rpo: "1h"
    rto: "4h"
spec:
  type: A
  ttl: 60  # Short TTL for quick failover
  records:
    - 198.51.100.10
    - 198.51.100.11
  zoneRef:
    name: company.com
    kind: ClusterZone
  comment: "Disaster recovery site"
