# RRset Examples for PowerDNS Operator
# This file demonstrates various RRset (Resource Record Set) configurations

---
# Example 1: Basic A Record
# Simple A record pointing to an IP address
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: www-example-com
  namespace: default
  labels:
    record-type: A
    service: web
  annotations:
    description: "Main website A record"
    owner: "web-team@company.com"
spec:
  # DNS record type
  type: A
  # Time to Live (seconds)
  ttl: 300
  # IP addresses
  records:
    - 192.168.1.100
    - 192.168.1.101
  # Reference to the zone
  zoneRef:
    name: example.com
    kind: Zone
  # Optional comment
  comment: "Load balanced web servers"

---
# Example 2: CNAME Record
# Canonical name record for aliases
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: blog-example-com
  namespace: default
  labels:
    record-type: CNAME
    service: blog
spec:
  type: CNAME
  ttl: 3600
  records:
    - www.example.com
  zoneRef:
    name: example.com
    kind: Zone
  comment: "Blog alias pointing to main website"

---
# Example 3: Multiple A Records (Load Balancing)
# Multiple IP addresses for load balancing
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: api-example-com
  namespace: production
  labels:
    record-type: A
    service: api
    environment: production
  annotations:
    description: "API endpoint with load balancing"
    load-balancer: "round-robin"
spec:
  type: A
  ttl: 120  # Shorter TTL for faster failover
  records:
    - 10.0.1.10
    - 10.0.1.11
    - 10.0.1.12
  zoneRef:
    name: example.com
    kind: Zone
  comment: "API servers with health checks"

---
# Example 4: MX Records (Mail Exchange)
# Mail server configuration
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: mail-example-com
  namespace: default
  labels:
    record-type: MX
    service: mail
spec:
  type: MX
  ttl: 3600
  records:
    - "10 mail1.example.com"
    - "20 mail2.example.com"
    - "30 mail3.example.com"
  zoneRef:
    name: example.com
    kind: Zone
  comment: "Mail servers with priority"

---
# Example 5: TXT Records (SPF, DKIM, etc.)
# Text records for email authentication
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: spf-example-com
  namespace: default
  labels:
    record-type: TXT
    purpose: spf
spec:
  type: TXT
  ttl: 3600
  records:
    - "v=spf1 include:_spf.google.com include:mailgun.org ~all"
  zoneRef:
    name: example.com
    kind: Zone
  comment: "SPF record for email authentication"

---
# Example 6: AAAA Records (IPv6)
# IPv6 address records
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: ipv6-example-com
  namespace: default
  labels:
    record-type: AAAA
    ip-version: ipv6
spec:
  type: AAAA
  ttl: 300
  records:
    - "2001:db8::1"
    - "2001:db8::2"
  zoneRef:
    name: example.com
    kind: Zone
  comment: "IPv6 addresses for www"

---
# Example 7: SRV Records (Service Discovery)
# Service location records
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: sip-tcp-example-com
  namespace: default
  labels:
    record-type: SRV
    service: sip
    protocol: tcp
spec:
  type: SRV
  ttl: 3600
  records:
    - "10 60 5060 sip1.example.com"
    - "10 40 5060 sip2.example.com"
  zoneRef:
    name: example.com
    kind: Zone
  comment: "SIP service discovery"

---
# Example 8: PTR Records (Reverse DNS)
# Reverse DNS lookup records
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: reverse-100-1-168-192
  namespace: default
  labels:
    record-type: PTR
    purpose: reverse-dns
spec:
  type: PTR
  ttl: 3600
  records:
    - "server1.example.com"
  zoneRef:
    name: 1.168.192.in-addr.arpa
    kind: Zone
  comment: "Reverse DNS for 192.168.1.100"

---
# Example 9: Wildcard Record
# Wildcard DNS record
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: wildcard-example-com
  namespace: default
  labels:
    record-type: A
    wildcard: "true"
  annotations:
    description: "Wildcard record for catch-all subdomains"
spec:
  type: A
  ttl: 300
  records:
    - 192.168.1.200
  zoneRef:
    name: example.com
    kind: Zone
  comment: "Wildcard record for *.example.com"

---
# Example 10: Development Environment Records
# Records for development services
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: dev-api-example-com
  namespace: development
  labels:
    record-type: A
    service: api
    environment: development
  annotations:
    description: "Development API endpoint"
    auto-cleanup: "enabled"
spec:
  type: A
  ttl: 60  # Very short TTL for development
  records:
    - 10.10.1.100
  zoneRef:
    name: dev.example.com
    kind: Zone
  comment: "Development API server"

---
# Example 11: Microservice Discovery
# Records for microservice communication
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: user-service
  namespace: microservices
  labels:
    record-type: A
    service: user-service
    team: backend
  annotations:
    description: "User microservice endpoint"
    health-check: "enabled"
spec:
  type: A
  ttl: 30  # Very short for service discovery
  records:
    - 10.20.1.50
    - 10.20.1.51
  zoneRef:
    name: services.example.com
    kind: Zone
  comment: "User service instances"

---
# Example 12: Database Connection Records
# Records for database endpoints
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: db-primary
  namespace: database
  labels:
    record-type: A
    service: database
    role: primary
  annotations:
    description: "Primary database endpoint"
    backup-priority: "high"
spec:
  type: A
  ttl: 300
  records:
    - 10.30.1.10
  zoneRef:
    name: db.example.com
    kind: Zone
  comment: "Primary database server"

---
# Example 13: CDN Configuration
# Records for CDN endpoints
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: cdn-example-com
  namespace: default
  labels:
    record-type: CNAME
    service: cdn
  annotations:
    description: "CDN endpoint for static assets"
spec:
  type: CNAME
  ttl: 3600
  records:
    - d1234567890.cloudfront.net
  zoneRef:
    name: example.com
    kind: Zone
  comment: "CloudFront CDN distribution"

---
# Example 14: Health Check Endpoint
# Records for health monitoring
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: health-example-com
  namespace: monitoring
  labels:
    record-type: A
    service: health-check
  annotations:
    description: "Health check endpoint"
    monitoring: "enabled"
spec:
  type: A
  ttl: 60
  records:
    - 10.40.1.100
  zoneRef:
    name: example.com
    kind: Zone
  comment: "Health check service"

---
# Example 15: Regional Load Balancer
# Records for geographical load balancing
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: us-west-api
  namespace: us-west
  labels:
    record-type: A
    service: api
    region: us-west
  annotations:
    description: "US West API endpoint"
    geo-location: "us-west"
spec:
  type: A
  ttl: 180
  records:
    - 10.50.1.10
    - 10.50.1.11
  zoneRef:
    name: us-west.example.com
    kind: Zone
  comment: "US West region API servers"

---
# Example 16: DKIM TXT Record
# DKIM email authentication record
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: dkim-selector
  namespace: default
  labels:
    record-type: TXT
    purpose: dkim
spec:
  type: TXT
  ttl: 3600
  records:
    - "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC..."
  zoneRef:
    name: example.com
    kind: Zone
  comment: "DKIM public key for email signing"

---
# Example 17: CAA Record
# Certificate Authority Authorization
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: caa-example-com
  namespace: default
  labels:
    record-type: CAA
    purpose: ssl-policy
spec:
  type: CAA
  ttl: 3600
  records:
    - "0 issue letsencrypt.org"
    - "0 issue digicert.com"
    - "0 iodef mailto:security@example.com"
  zoneRef:
    name: example.com
    kind: Zone
  comment: "Certificate Authority Authorization"

---
# Example 18: Blue-Green Deployment
# Records for blue-green deployment strategy
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: app-blue
  namespace: production
  labels:
    record-type: A
    service: application
    deployment: blue
  annotations:
    description: "Blue deployment endpoint"
    deployment-strategy: "blue-green"
spec:
  type: A
  ttl: 60  # Short TTL for quick switching
  records:
    - 10.60.1.10
    - 10.60.1.11
  zoneRef:
    name: example.com
    kind: Zone
  comment: "Blue deployment servers"

---
# Example 19: Canary Deployment
# Records for canary deployment
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: app-canary
  namespace: production
  labels:
    record-type: A
    service: application
    deployment: canary
  annotations:
    description: "Canary deployment endpoint"
    traffic-percentage: "10"
spec:
  type: A
  ttl: 30  # Very short for canary testing
  records:
    - 10.60.2.10
  zoneRef:
    name: canary.example.com
    kind: Zone
  comment: "Canary deployment server"

---
# Example 20: Monitoring and Alerting
# Records for monitoring services
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: RRset
metadata:
  name: prometheus-example-com
  namespace: monitoring
  labels:
    record-type: A
    service: prometheus
    component: monitoring
  annotations:
    description: "Prometheus monitoring endpoint"
    scrape-interval: "30s"
spec:
  type: A
  ttl: 300
  records:
    - 10.70.1.10
  zoneRef:
    name: monitoring.example.com
    kind: Zone
  comment: "Prometheus monitoring server"
